export const TAGS = {
  ROUTE_PREFIX: 'ROUTE_PREFIX',
  ROUTE_PATH: 'ROUTE_PATH',
  ROUTE_PARAMS: 'ROUTE_PARAMS',
  ROUTE_PARAMS_TYPE: 'design:paramtypes',
  RENDER_TEMPLATE: 'RENDER_TEMPLATE'
}

export const ROUTE_PARAMS_SOURCE = {
  QUERY: 'QUERY',
  BODY: 'BODY'
}